version: '3.8'
services:
  processgraph.api:
    image: processgraph.api
    container_name: ProcessGraph.API
    build:
      context: .
      dockerfile: ProcessGraph.API/Dockerfile
    depends_on:
      - process-graph-db
  process-graph-db:
    image: mongodb/mongodb-community-server
    container_name: process-graph-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

